//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Blend.SampleData.SampleDataSource
{
    using System; 
    using System.ComponentModel;

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
    internal class SampleDataSource { }
#else

    public class SampleDataSource : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (this.PropertyChanged != null)
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        public SampleDataSource()
        {
            try
            {
                Uri resourceUri = new Uri("ms-appx:/SampleData/SampleDataSource/SampleDataSource.xaml", UriKind.RelativeOrAbsolute);
                Windows.UI.Xaml.Application.LoadComponent(this, resourceUri);
            }
            catch
            {
            }
        }

        private string _HomeTeamName = string.Empty;

        public string HomeTeamName
        {
            get
            {
                return this._HomeTeamName;
            }

            set
            {
                if (this._HomeTeamName != value)
                {
                    this._HomeTeamName = value;
                    this.OnPropertyChanged("HomeTeamName");
                }
            }
        }

        private string _AwayTeamName = string.Empty;

        public string AwayTeamName
        {
            get
            {
                return this._AwayTeamName;
            }

            set
            {
                if (this._AwayTeamName != value)
                {
                    this._AwayTeamName = value;
                    this.OnPropertyChanged("AwayTeamName");
                }
            }
        }
    }
#endif
}
